Feature/erd-research-document
cypherkrescent/inventor-be pull request #10
Opened 2023-11-07 14:14 UTC by Daveohi

Documentation on ERD research
https://github.com/Daveohi/inventor-be/wiki/ERD-Documentation-(David)

2023-11-07 14:22 UTC, Adeola-Aderibigbe requested changes
Only open 1 pr for one issue. 

-  Put the erd link into a text. eg [ERD](https://online.visual-paradigm.com/share.jsp?id=323232313032392d35#diagram:workspace=jllhkccg&proj=0&id=5)

2023-11-07 15:15 UTC, Adeola-Aderibigbe commented on README.md
> +![Entity Relationship Diagram](![SoftwareIntern_Inventor](https://github.com/cypherkrescent/inventor-be/assets/78306383/a17fba1b-ff38-4367-8cbf-dd3ae9f28d64)
- The image isn't displayed 
- Open one pr for a issue
- Attach this pr to issue #1 . check out [Closing Keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

@Daveohi

2023-11-10 11:04 UTC, Gwenyfar requested changes
Please link the required issue to this PR

2023-11-10 13:05 UTC, Gwenyfar approved these changes

2023-11-10 13:05 UTC, Adeola-Aderibigbe approved these changes

2023-11-10 13:06 UTC, merged