Update README.md
cypherkrescent/inventor-be pull request #11
Opened 2023-11-07 15:16 UTC by Daveohi

Documentation on Architectural Pattern

2023-11-07 15:28 UTC, Adeola-Aderibigbe requested changes
Pls name your wiki page correctly. Check out [Wiki-page tutorial](https://github.com/cypherkrescent/inventor-be/wiki/1.-Wiki-Template)

2023-11-07 15:39 UTC, Gwenyfar requested changes

2023-11-07 15:39 UTC, Gwenyfar commented on README.md
> +# Research documentation on Architectural Pattern
Don't use heading 1 for this. It should be a sub heading.
Please do same for your other PRs

2023-11-20 09:58 UTC, Gwenyfar approved these changes

2023-11-20 09:59 UTC, merged